dist: bionic
language: csharp
dotnet: "3.1"
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - PATH="$PATH:$HOME/.dotnet/tools"

script:
 - dotnet restore
 - dotnet build --no-restore
 - dotnet test --no-restore
